document.addEventListener('DOMContentLoaded', () => {
    const newsContainer = document.getElementById('news-container');
    const dateDisplay = document.getElementById('date-display');
    const catButtons = document.querySelectorAll('.cat-btn');

    // Set current date
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    dateDisplay.textContent = new Date().toLocaleDateString('en-US', options);

    let allNews = [];

    async function fetchNews() {
        try {
            // Fetch news from news.json (generated by GitHub Actions)
            const response = await fetch('news.json');
            if (!response.ok) throw new Error('Failed to fetch news');
            
            const data = await response.json();
            allNews = data.articles;
            renderNews(allNews);
        } catch (error) {
            console.error('Error:', error);
            newsContainer.innerHTML = `
                <div class="loader">
                    <p style="color: #ff4b4b">Unable to load news. Please check back later.</p>
                </div>
            `;
        }
    }

    function renderNews(articles) {
        if (articles.length === 0) {
            newsContainer.innerHTML = '<p class="loader">No stories found for this category.</p>';
            return;
        }

        newsContainer.innerHTML = articles.map((article, index) => `
            <article class="news-card" style="animation-delay: ${index * 0.1}s">
                <span class="badge">${article.category}</span>
                <h2>${article.title}</h2>
                <p>${article.summary}</p>
                <a href="${article.url}" target="_blank" class="read-more">Source Article</a>
            </article>
        `).join('');
    }

    catButtons.forEach(btn => {
        btn.addEventListener('click', () => {
            // Update active state
            catButtons.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');

            const category = btn.getAttribute('data-category');
            if (category === 'all') {
                renderNews(allNews);
            } else {
                const filtered = allNews.filter(a => a.category.toLowerCase() === category);
                renderNews(filtered);
            }
        });
    });

    fetchNews();
});
